name: HavaPouce
version: '${project.version}'
main: pouce.HavaPouce
api-version: '1.20'
authors: [MrPouceBleu]
commands:
  gui:
    description: Commande pour ouvrir une interface utilisateur
    usage: /gui
  guitem:
    description: Commande pour crée un item d'interface
    usage: /guitem
  havadev:
    description: Commande pour changer le mod de developpement
    usage: /havadev
  nav:
    description: Affiche le menu de navigation
    usage: /nav
  nbt:
    description: Permet de manipuler les nbt
    usage: /ntb
  donjonitems:
    description: permet de manipuler les items donjon
    usage: /donjonitems
  vision:
    description: permet de toggle un effet de night vision
    usage: /vision


