name: HavaPouce
version: '${project.version}'
main: pouce.HavaPouce
api-version: '1.20'
authors: [MrPouceBleu]
commands:
  gui:
    description: Commande pour ouvrir une interface utilisateur
    usage: /gui
  guitem:
    description: Commande pour crée un item d'interface
    usage: /guitem
  havadev:
    description: Commande pour changer le mod de developpement
    usage: /havadev
  nav:
    description: Affiche le menu de navigation
    usage: /nav
  setnbt:
    description: Permet d'ajouter des NTB a un item
    usage: /setntb <key> <value>
  clearnbt:
    description: Supprime tous les NBT de l'item en main.
    usage: /clearntb

